apiVersion: v1
kind: Namespace
metadata:
  name: prod-ml-app
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prod-ml-predict-rc
  labels:
    app: prod-ml-predict
    env: prod    
  namespace: prod-ml-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: prod-ml-predict
        env: prod
      namespace: prod-ml-app
    spec:
      containers:
      - image: bird5555/carbon-api
        name: prod-ml-predict-api
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prod-ml-predict-lb
  labels:
    app: prod-ml-predict
  namespace: prod-ml-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: prod-ml-predict
