# Default values for helm-ml-carbon-predict-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
app:
  name: prod-ml-predict
  env: prod
  namespace: prod-ml-app
  image: bird5555/carbon-api

replicas: 2
containerPort: 5000
targetPort: 5000
